INSERT INTO `PhamilyFotos`.`MemberFotos` (`id`, `memberId`, `fotoId`) 
VALUES (NULL, '1', '3'), 
(NULL, '1', '4'),
(NULL, '1', '5'),
(NULL, '1', '6'),
(NULL, '1', '7'),
(NULL, '1', '8'),
(NULL, '1', '9'),
(NULL, '1', '10'),
(NULL, '1', '11'),
(NULL, '1', '12'),
(NULL, '1', '13'),
(NULL, '1', '14'),
(NULL, '1', '15'),
(NULL, '1', '16'),
(NULL, '1', '17'),
(NULL, '1', '18'),
(NULL, '1', '19'),
(NULL, '1', '20'),
(NULL, '1', '21'),
(NULL, '1', '22'),
(NULL, '1', '23'),
(NULL, '1', '24'),
(NULL, '1', '25'),
(NULL, '1', '26'),
(NULL, '1', '27'),
(NULL, '1', '28'),
(NULL, '1', '29'),
(NULL, '1', '30'),
(NULL, '1', '31'),
(NULL, '1', '32');

INSERT INTO 'PhamilyFotos'.'Foto' ('id', 'FotoName', 'Caption', 'path', 'userId', 'albumId')
VALUES (NULL, 'image33', 'NULL', 'images/small/', '2', '3'),
(NULL, 'image33', NULL, 'images/small/', '2', '3'),
(NULL, 'image34', NULL, 'images/small/', '2', '3'),
(NULL, 'image35', NULL, 'images/small/', '2', '3'),
(NULL, 'image36', NULL, 'images/small/', '2', '3'),
(NULL, 'image37', NULL, 'images/small/', '2', '3'),
(NULL, 'image38', NULL, 'images/small/', '2', '3'),
(NULL, 'image39', NULL, 'images/small/', '2', '3'),
(NULL, 'image40', NULL, 'images/small/', '2', '3'),
(NULL, 'image41', NULL, 'images/small/', '2', '3'),
(NULL, 'image42', NULL, 'images/small/', '2', '3'),
(NULL, 'image43', NULL, 'images/small/', '2', '3'),
(NULL, 'image44', NULL, 'images/small/', '2', '3');